### PR TITLE
setup

### PR DESCRIPTION
**Pull request by daviddassau**

### CODE REVIEW

**Comment by daviddassau** [comment]
Sorry, I meant to name this branch test

**Comment by daviddassau** [comment]
Firebase link: https://angular-contacts-db03c.firebaseapp.com

**Comment by daviddassau** [comment]
Can't get my background color to show up

**Comment by rousell** [comment]
hi @daviddassau! it looks like your deployed site doesn't have the contents of the main.css file pulling through -- try cleaning your deployment and redoing it with your current code.

the only other little thing is that your routes should be like 'contacts/new'. let me know when you've changed that and the associated code :)

**Comment by daviddassau** [comment]
@rousell CSS should be working now!

As far as the three html files being in a contacts directory, Zoe said that we didn't have to have the contacts directory for this assignment.

**Comment by rousell** [comment]
@daviddassau you're right, the thing that you need to change is the routes. so if i go to your deployed app and I go to {{url}}/contacts/new, i should get the new.html page

**Comment by rousell** [comment]
you'll be changing the value within the '.when('xxx')' in your AppConfig

**Review by morecallan — APPROVED** [review]

**Pull request merged**
